import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Thanh Xuân",
  description: "Generated by create next app",
}; 

export default function Home() {
  return (
    <div>
      <h1 className="text-5xl">Welcome Nam Dep trai</h1>
    </div>
  );
}
